commerce_product_review.commerce_product_review_type.*:
  type: config_entity
  label: 'Product review type'
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    description:
      type: text
      label: Description
    descriptionPlaceholder:
      type: text
      label: 'Description placeholder text'
    notificationEmail:
      type: string
      label: 'The notification email address(es)'
    productTypes:
      type: sequence
      label: 'Product types'
      sequence:
        type: string
        label: 'Product type'

field.formatter.settings.commerce_product_review_overall_rating_default:
  type: mapping
  mapping:
    strip_trailing_zeroes:
      type: boolean
      label: 'Strip trailing zeroes after the decimal point'
    empty_text:
      type: string
      label: 'Text displayed, if no published review exists for the given product.'

field.formatter.settings.commerce_product_review_overall_rating_stars:
  type: mapping
  mapping:
    show_overview_link:
      type: boolean
      label: 'Whether to display a link to the product''s review overview page.'
    show_review_form_link:
      type: boolean
      label: 'Whether to display a link to the review form.'
    empty_text:
      type: string
      label: 'Text displayed, if no published review exists for the given product.'
