field.formatter.settings.slideshow:
  type: mapping
  label: 'Field slideshow'
  mapping:
    colorbox_image_style:
      type: string
      label: 'Colorbox Image Style'
    slideshow:
      fx:
        type: string
        label: 'Transition'
      allowWrap:
        type: boolean
        label: 'Allow wrap'
      deley:
        type: string
        label: 'Deley'
      hideNonActive:
        type: boolean
        label: 'Hide Non Active'
      loader:
        type: string
        label: 'Loader'
      loop:
        type: integer
        label: 'Loop'
      pauseOnHover:
        type: boolean
        label: 'Pause On Hover'
      paused:
        type: boolean
        label: 'Paused'
      random:
        type: boolean
        label: 'Random'
      reverse:
        type: boolean
        label: 'Reverse'
      speed:
        type: integer
        label: 'Speed'
      startingSlide:
        type: integer
        label: 'Starting Slide'
      swipe:
        type: boolean
        label: 'Swipe'
      sync:
        type: boolean
        label: 'Sync'
      timeout:
        type: integer
        label: 'Timeout'
    slideshow_pager:
      pager_type:
        type: string
        label: 'Pager type'
      pager:
        type: string
        label: 'Pager'
      controls:
        type: boolean
        label: 'Controls'
