name: ddev-mynewdrupal
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        name: ddev-mynewdrupal_default
services:
    db:
        build:
            args:
                BASE_IMAGE: drud/ddev-dbserver-mariadb-10.4:v1.21.5
                gid: "1000"
                uid: "1000"
                username: vadik
            context: /home/vadik/mynewdrupal/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-mynewdrupal-db
        environment:
            COLUMNS: "80"
            DDEV_DATABASE: mariadb:10.4
            DDEV_HOSTNAME: mynewdrupal.ddev.site
            DDEV_PHP_VERSION: "8.1"
            DDEV_PRIMARY_URL: https://mynewdrupal.ddev.site
            DDEV_PROJECT: mynewdrupal
            DDEV_PROJECT_TYPE: drupal9
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: mynewdrupal
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "24"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/mynewdrupal-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: ""
            USER: vadik
        healthcheck:
            interval: 1s
            retries: 120
            start_period: 2m0s
            timeout: 2m0s
        hostname: mynewdrupal-db
        image: drud/ddev-dbserver-mariadb-10.4:v1.21.5-mynewdrupal-built
        labels:
            com.ddev.app-type: drupal9
            com.ddev.approot: /home/vadik/mynewdrupal
            com.ddev.platform: ddev
            com.ddev.site-name: mynewdrupal
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "32770"
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: 1000:1000
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /home/vadik/mynewdrupal/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /home/vadik/mynewdrupal/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/vadik
    dba:
        container_name: ddev-mynewdrupal-dba
        environment:
            HTTP_EXPOSE: 8036:80
            HTTPS_EXPOSE: 8037:80
            PMA_PASSWORD: root
            PMA_USER: root
            TZ: ""
            UPLOAD_LIMIT: 1024M
            VIRTUAL_HOST: mynewdrupal.ddev.site
        expose:
            - "80"
        healthcheck:
            interval: 2m0s
            retries: 1
            timeout: 2s
        hostname: mynewdrupal-dba
        image: phpmyadmin:5
        labels:
            com.ddev.app-type: drupal9
            com.ddev.approot: /home/vadik/mynewdrupal
            com.ddev.platform: ddev
            com.ddev.site-name: mynewdrupal
        networks:
            ddev_default: null
            default: null
        restart: "no"
        working_dir: /root
    web:
        build:
            args:
                BASE_IMAGE: drud/ddev-webserver:v1.21.5
                DDEV_PHP_VERSION: "8.1"
                gid: "1000"
                uid: "1000"
                username: vadik
            context: /home/vadik/mynewdrupal
            dockerfile: ./.ddev/.webimageBuild/Dockerfile
        cap_add:
            - SYS_PTRACE
        container_name: ddev-mynewdrupal-web
        environment:
            COLUMNS: "80"
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.4
            DDEV_DOCROOT: web
            DDEV_FILES_DIR: /var/www/html/web/sites/default/files
            DDEV_HOSTNAME: mynewdrupal.ddev.site
            DDEV_MUTAGEN_ENABLED: "false"
            DDEV_PHP_VERSION: "8.1"
            DDEV_PRIMARY_URL: https://mynewdrupal.ddev.site
            DDEV_PROJECT: mynewdrupal
            DDEV_PROJECT_TYPE: drupal9
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: mynewdrupal
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.21.5
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: web
            DRUSH_ALLOW_XDEBUG: "1"
            DRUSH_OPTIONS_URI: https://mynewdrupal.ddev.site
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "24"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/mynewdrupal-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=mynewdrupal.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: ""
            USER: vadik
            VIRTUAL_HOST: mynewdrupal.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:mynewdrupal.ddev.site
        extra_hosts:
            - host.docker.internal:host-gateway
        healthcheck:
            interval: 1s
            retries: 120
            start_period: 2m0s
            timeout: 2m0s
        hostname: mynewdrupal-web
        image: drud/ddev-webserver:v1.21.5-mynewdrupal-built
        labels:
            com.ddev.app-type: drupal9
            com.ddev.approot: /home/vadik/mynewdrupal
            com.ddev.platform: ddev
            com.ddev.site-name: mynewdrupal
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
        restart: "no"
        user: 1000:1000
        volumes:
            - consistency: cached
              source: ../
              target: /var/www/html
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/vadik/mynewdrupal/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/vadik/mynewdrupal/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: mynewdrupal-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
